### ISSUE TITLE
Users without peaqev seem to lack offsets from core-service-hoursselection

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqhvac#58]
This is how mince looks like, seems to be missing some data?

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/85b82fd2-c9f2-4bf9-bd1a-180809251c43)

_Originally posted by @enoch85 in https://github.com/elden1337/hass-peaqhvac/issues/55#issuecomment-1777078901_

**Comment by elden1337** [comment]
@enoch85 if you open up sensor.peaqhvac_calculated_hvac_offset and look at the attributes, are you getting anything there at all? 

Or is it that you havent gotten nordpool but only energidataservice installed? That fet is not done yet so it wont work with that im afraid. 

A screenshot would help alot. Thanks

**Comment by enoch85** [comment]
![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/0af39d88-d461-4e30-b1a4-2db83bc11d74)

I have both Nordpool and Energi Data Service installed.

**Comment by enoch85** [comment]
![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/a7f14676-adc8-474d-b120-c2bbeefc8ee3)

**Comment by elden1337** [comment]
;), this sensor please `sensor.peaqhvac_calculated_hvac_offset`

**Comment by elden1337** [comment]
proposed fix in https://github.com/elden1337/hass-peaqhvac/releases/tag/2.0.4
@enoch85 closes this once he's seen that he's getting the offsets (works on my machine)

**Comment by enoch85** [comment]
Sorry to say it still doesn't work:

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/82d56af2-52cd-44af-a603-590e7cca368b)

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/1b6a76aa-9f7f-4716-88dc-ef8795f122d7)

### Tested
0.1 Installed the update
1. Reboot HAOS
2. Reboot the server completley
3. Forced refresh (CTRL+F5) browser

It will water boost at 06:47. At least that's something. Would be better if it boosted at 4:00 though if you look at the curve. :)

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/23e1cfc8-19a2-4f05-a7e4-5123e045d04c)

**Comment by enoch85** [comment]
Some logs:


```
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:231
Integration: Sensor (documentation, issues)
First occurred: 22:20:43 (4 occurrences)
Last logged: 22:20:43

The unit of sensor.peaqev_energy_cost_integral_daily (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.peaqev_energy_including_car_daily (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.peaqev_energy_including_car_hourly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.peaqev_energy_excluding_car_hourly (kWh) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this


Logger: homeassistant.helpers.event
Source: helpers/event.py:293
First occurred: 22:20:42 (95 occurrences)
Last logged: 22:33:35

Error while dispatching event for sensor.peaqev_energy_cost_integral to <Job track state_changed event ['sensor.peaqev_energy_cost_integral'] HassJobType.Callback <bound method UtilityMeterSensor.async_reading of <entity sensor.peaqev_energy_cost_integral_monthly=unknown>>>
Error while dispatching event for sensor.peaqev_energy_including_car to <Job track state_changed event ['sensor.peaqev_energy_including_car'] HassJobType.Callback <bound method UtilityMeterSensor.async_reading of <entity sensor.peaqev_energy_including_car_monthly=unknown>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 293, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 636, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/utility_meter/sensor.py", line 484, in async_reading
    for sensor in self.hass.data[DATA_UTILITY][self._parent_meter][
                  ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'utility_meter_data'


Logger: homeassistant.helpers.entity
Source: helpers/entity.py:732
First occurred: 22:20:06 (203 occurrences)
Last logged: 22:33:35

Update for sensor.peaqev_my_savings_this_month fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in async_device_update
    await self.async_update()
  File "/config/custom_components/peaqev/sensors/simple_money_sensor.py", line 44, in async_update
    ret = getattr(self.hub.spotprice, self._caller_attribute)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peaqev/peaqservice/hub/spotprice/spotpricebase.py", line 103, in savings_month
    return round(float(month_draw.state) * month_diff,3)
                 ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'


Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:143
First occurred: 22:22:42 (6 occurrences)
Last logged: 22:32:42

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OffsetModel.recalculate_tolerance() takes 1 positional argument but 2 were given


```

**Comment by elden1337** [comment]
All but the last of these is from peaqev. Errors ive never seen before. 
Please uninstall peaqev (since you dont use it) and try again. The last issue there will remain once every 2min but shouldnt be sn issue beyond itself.

**Comment by enoch85** [comment]
PeaqEV disabled and removed from HACS as well.

Some more logs:

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/170362ef-27cc-4320-a1b4-1be3e68369b0)

**Comment by enoch85** [comment]
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/peaqhvac/service/hvac/offset/offset_coordinator.py:79
Integration: peaqhvac (documentation, issues)
First occurred: 23:23:53 (134 occurrences)
Last logged: 23:26:06

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/peaqhvac/service/observer/observer_service.py", line 64, in async_dispatch
    await self.async_dequeue_and_broadcast(q)
  File "/config/custom_components/peaqhvac/service/observer/observer_service.py", line 76, in async_dequeue_and_broadcast
    await self.hub.state_machine.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peaqhvac/service/observer/observer_service.py", line 95, in _call_func
    func(command.argument)
  File "/config/custom_components/peaqhvac/service/hvac/offset/offset_coordinator.py", line 79, in _update_prices
    self.hours.update_prices(prices[0], prices[1])
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Hoursselection' object has no attribute 'update_prices'

```

**Comment by enoch85** [comment]
A few more days test data:

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/5843d0ec-bace-471e-95f8-b77d40fb767e)


I think this can be closed?

**Comment by enoch85** [comment]
Hmm just tried to add the Apexchart, and I can't find the hour_controler? 

`Entity not available: sensor.peaqev_hour_controller`

What is the equivalent in hvac?

**Comment by enoch85** [comment]
I added the `average spotpris` sensor instead, and finally got this:

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/1f0a4295-9b21-4738-bb8d-5286460c287b)

**Comment by elden1337** [comment]
Ok good. But do you see them as attributes on the sensor then?! I thought they were blank for you!

**Comment by elden1337** [comment]
Ah yes. I see now. I miss comments sometimes in the large influx.

**Comment by enoch85** [comment]
Question remains, 

> Entity not available: sensor.peaqev_hour_controller

What is the equivalent in hvac? I just picked a random sensor to get the Apex chart up and running...

**Comment by elden1337** [comment]
There is none currently. Peaqhvac does not have that data itself since those are handled by peaqev.
